config/routes.rb
Rails.application.routes.draw do
  root 'admin/homes#index'
  namespace :admin do
    resources :dashboard
    resources :productions
    resources :payments
    resources :posts
    resources :homes
    resources :suppliers
    resources :customers
    resources :invoices

    devise_for :users, controllers: {
      sessions: 'admin/users/sessions' ,
      registrations: 'admin/users/registrations',
    }
  end

  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :invoices

  def name_with_contact
    "#{name}" " , #{contact}"
  end
end

app/models/import.rb
class Import < ApplicationRecord
  belongs_to :supplier
  has_many :import_details
  has_many :products , through: import_details
end

app/models/import_detail.rb
class ImportDetail < ApplicationRecord
  belongs_to :product
  belongs_to :import
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :payments
  accepts_nested_attributes_for :payments, :allow_destroy => true, :reject_if => :all_blank
  has_many :productions, inverse_of: :invoice
  accepts_nested_attributes_for :productions, :allow_destroy => true, :reject_if => :all_blank

  def self.total_price_in_invoice(invoice)
    total = 0
      invoice.productions.each do |productions|
      total = productions.width * productions.length * productions.price
    end
    return total
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :invoice
  def self.total_price_in_payment(invoice)
    payments = where(invoice: invoice)
    total =0;
    payments.each do |payment|
      total = total + payment.amount
    end
    return total
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :import_details
  has_many :imports , through: :import_details
end

app/models/production.rb
class Production < ApplicationRecord
  belongs_to :invoice ,optional: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :imports
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end
  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to [:admin,@customer]
    end
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to root_path
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to admin_customers_path
  end

  private
  def customer_params
    params.require(:customer).permit(:id,:name,:address,:contact)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::ApplicationController
  def index
    
  end
end

app/controllers/admin/invoices_controller.rb
class Admin::InvoicesController < Admin::ApplicationController
  include ApplicationHelper

  def index
    @invoices = Invoice.all
  end

  def show
    @invoice = Invoice.find(params[:id])
    @total_price = Invoice.total_price_in_invoice(@invoice)
    @payments = Payment.where(invoice: @invoice)
    @payment_total = Payment.total_price_in_payment(@invoice)
    
    @balance = ApplicationHelper.check_balance(@payment_total,@invoice.deposit)
  end

  def new
    @invoice = Invoice.new
    @invoice.productions.build
  end

  def create
    @invoice = Invoice.create(invoice_params)
    if @invoice.save
      @payment = Payment.new
      @payment.invoice = @invoice
      @payment.paid_date = @invoice.release_date
      @payment.amount = @invoice.deposit

      @invoice.total = Invoice.total_price_in_invoice(@invoice)
      if @payment.save && @invoice.save
        redirect_to admin_invoices_path
      end
    end
  end

  def test
    @invoice = Invoice.new
  end

  private
  def invoice_params
    params.require(:invoice).permit(:id,:customer_id,:release_date,:deposit,:production_id,productions_attributes:[:id,:_destroy,:name,:quantity,:width,:length,:price])
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :authenticate_admin_user!
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/invoices_helper.rb
module Admin::InvoicesHelper



end

app/helpers/admin/payments_helper.rb
module Admin::PaymentsHelper
end

app/helpers/admin/productions_helper.rb
module Admin::ProductionsHelper
end

app/helpers/admin/suppliers_helper.rb
module Admin::SuppliersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def self.check_balance(total,deposit)
    if total < deposit && total < deposit - 5
      return "PAID"
    else
      return total -  deposit
    end

  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/customers/_form.html.erb
<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        New Customer Form
      </h1>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">
            <i class="fa fa-dashboard"></i>
            Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#">Forms</a>
        </li>
        <li class="breadcrumb-item active">General Elements</li>
      </ol>
    </section>
    <div class="content">
      <div class="box box-warning">
        <div class="box-header with-border">
          <h3 class="box-title">Add New Customer</h3>
        </div>
        <!-- /.box-header -->

        <div class="box-body">

          <%= form_for ([:admin,@customer]) do |f| %>
          <div class="form-group">
            <%= f.label :name%>
            <%= f.text_field :name , class:"form-control" , placeholder: "Enter Name"%>
          </div>
          <div class="form-group">
            <%= f.label :address%>
            <%= f.text_field :address , class:"form-control" , placeholder: "Enter Address"%>
          </div>
          <div class="form-group">
            <%= f.label :contact%>
            <%= f.text_area :contact , class:"form-control" , placeholder: "Enter Contact"%>
          </div>
          <div class="form-group">
            <%= f.submit  class: "btn btn-lg btn-primary" %>
          </div>
          <% end %>
        </div>
        <!-- Box Body-->

      </div>
    </div>
  </div>
</div>
</div>

app/views/admin/customers/edit.html.erb
<%= render 'form' %>

app/views/admin/customers/index.html.erb
<div class="wrapper">
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Our Customers
      </h1>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">
            <i class="fa fa-dashboard"></i>
            Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#">Forms</a>
        </li>
        <li class="breadcrumb-item active">General Elements</li>
      </ol>
    </section>
    <div class="content">
      <div class="col-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">List Customers</h3><br><br>
            <%= link_to "New Customer" , new_admin_customer_path , class: "btn btn-primary"%><br>
            <div class="box-tools">
              <div class="input-group input-group-sm" style="width: 150px;">
                <input name="table_search" class="form-control pull-right" placeholder="Search" type="text">
                <div class="input-group-btn">
                  <button type="submit" class="btn btn-default">
                    <i class="fa fa-search"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body no-padding">
            <table class="table table-hover table-responsive">
              <tbody>
                <tr>
                  <th>ID</th>
                  <th>User Name</th>
                  <th>Address</th>
                  <th>Contact</th>
                  <th>Created At</th>
                  <th>Action</th>
                </tr>
                <% @customers.each do |customer| %>
                <tr>
                  <td>
                    <a href="javascript:void(0)"><%= customer.id %></a>
                  </td>
                  <td><%= customer.name %></td>
                  <td>
                    <%= customer.address %>
                  </td>
                  <td><%= customer.contact %></td>
                  <td>
                    <span><%= customer.created_at %></span>
                  </td>
                  <td>
                    <%= link_to "View", admin_customer_path(customer) , class: "btn btn-sm btn-primary "%>
                    <%= link_to "Edit", edit_admin_customer_path(customer), class: "btn btn-sm btn-warning " %>
                    <%= link_to "Delete", admin_customer_path(customer), class: "btn btn-sm btn-danger " , method: :delete, data: {confirm: "Are you sure?"} %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/new.html.erb
<%= render 'form' %>

app/views/admin/customers/show.html.erb
<div class="wrapper">
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Our Customers
      </h1>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">
            <i class="fa fa-dashboard"></i>
            Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#">Forms</a>
        </li>
        <li class="breadcrumb-item active">General Elements</li>
      </ol>
    </section>
    <div class="content">
      <div class="col-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">List Customers</h3>

            <div class="box-tools">
              <div class="input-group input-group-sm" style="width: 150px;">
                <input name="table_search" class="form-control pull-right" placeholder="Search" type="text">

                <div class="input-group-btn">
                  <button type="submit" class="btn btn-default">
                    <i class="fa fa-search"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body no-padding">
            <table class="table table-hover table-responsive">
              <tbody>
                <tr>
                  <th>No</th>
                  <th>User Name</th>
                  <th>Address</th>
                  <th>Contact</th>
                  <th>Created At</th>
                  <th>Action</th>
                </tr>
                <tr>
                  <td>
                    <a href="javascript:void(0)"><%= @customer.id %></a>
                  </td>
                  <td><%= @customer.name %></td>
                  <td>
                    <span class="text-muted"><%= @customer.address %></span>
                  </td>
                  <td><%= @customer.contact %></td>
                  <td>
                    <span><%= @customer.created_at %></span>
                  </td>
                  <td>
                    <%= link_to "Edit", edit_admin_customer_path(@customer), class: "btn btn-sm btn-warning " %>
                    <%= link_to "Delete", admin_customer_path(@customer), class: "btn btn-sm btn-danger " , method: :delete, data: {confirm: "Are you sure?"} %>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
    </div>
  </div>
</div>