config/routes.rb
Rails.application.routes.draw do
  root 'admin/homes#index'
  namespace :admin do
    resources :dashboard
    resources :productions
    resources :payments
    resources :posts
    resources :homes
    resources :suppliers
    resources :customers
    resources :invoices

    devise_for :users, controllers: {
      sessions: 'admin/users/sessions' ,
      registrations: 'admin/users/registrations',
    }
  end

  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :invoices

  def name_with_contact
    "#{name}" " , #{contact}"
  end
end

app/models/import.rb
class Import < ApplicationRecord
  belongs_to :supplier
  has_many :import_details
  has_many :products , through: import_details
end

app/models/import_detail.rb
class ImportDetail < ApplicationRecord
  belongs_to :product
  belongs_to :import
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :payments
  accepts_nested_attributes_for :payments, :allow_destroy => true, :reject_if => :all_blank
  has_many :productions, inverse_of: :invoice
  accepts_nested_attributes_for :productions, :allow_destroy => true, :reject_if => :all_blank

  def self.total_price_in_invoice(invoice)
    total = 0
      invoice.productions.each do |productions|
      total = productions.width * productions.length * productions.price
    end
    return total
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :invoice
  def self.total_price_in_payment(invoice)
    payments = where(invoice: invoice)
    total =0;
    payments.each do |payment|
      total = total + payment.amount
    end
    return total
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :import_details
  has_many :imports , through: :import_details
end

app/models/production.rb
class Production < ApplicationRecord
  belongs_to :invoice ,optional: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :imports
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::ApplicationController
  def index
    
  end
end

app/controllers/admin/invoices_controller.rb
class Admin::InvoicesController < Admin::ApplicationController
  include ApplicationHelper

  def index
    @invoices = Invoice.all
  end

  def show
    @invoice = Invoice.find(params[:id])
    @total_price = Invoice.total_price_in_invoice(@invoice)
    @payments = Payment.where(invoice: @invoice)
    @payment_total = Payment.total_price_in_payment(@invoice)
    
    @balance = ApplicationHelper.check_balance(@payment_total,@invoice.deposit)
  end

  def new
    @invoice = Invoice.new
    @invoice.productions.build
  end

  def create
    @invoice = Invoice.create(invoice_params)
    if @invoice.save
      @payment = Payment.new
      @payment.invoice = @invoice
      @payment.paid_date = @invoice.release_date
      @payment.amount = @invoice.deposit

      @invoice.total = Invoice.total_price_in_invoice(@invoice)
      if @payment.save && @invoice.save
        redirect_to admin_invoices_path
      end
    end
  end

  def test
    @invoice = Invoice.new
  end

  private
  def invoice_params
    params.require(:invoice).permit(:id,:customer_id,:release_date,:deposit,:production_id,productions_attributes:[:id,:_destroy,:name,:quantity,:width,:length,:price])
  end
end

app/controllers/admin/payments_controller.rb
class Admin::PaymentsController < Admin::ApplicationController

  $invoice = nil

  def new
    @payment = Payment.new
    @invoice = Invoice.find(params[:id])
    $invoice = @invoice
  end
  def create
    if $invoice != nil
      @payment = Payment.create(payment_params)
      @payment.invoice = $invoice
      if @payment.save
        redirect_to admin_invoice_path($invoice)
      end
    else
      redirect_to root_path
    end
  end

  private
  def payment_params
    params.require(:payment).permit(:id,:paid_date,:amount,:invoice_id)

  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :authenticate_admin_user!
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/invoices_helper.rb
module Admin::InvoicesHelper



end

app/helpers/admin/payments_helper.rb
module Admin::PaymentsHelper
end

app/helpers/admin/productions_helper.rb
module Admin::ProductionsHelper
end

app/helpers/admin/suppliers_helper.rb
module Admin::SuppliersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def self.check_balance(total,deposit)
    if total < deposit && total < deposit - 5
      return "PAID"
    else
      return total -  deposit
    end

  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/invoices/_form.html.erb
<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Invoice
      </h1>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">
            <i class="fa fa-dashboard"></i>
            Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#">Forms</a>
        </li>
        <li class="breadcrumb-item active">General Elements</li>
      </ol>
    </section>
    <div class="content">
      <div class="box box-warning">
        <div class="box-header with-border">
          <h3 class="box-title">Create Invoice</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body" style="padding:10px 20px;">
          <div class="row">
            <div class="col-md-12">
              <%= simple_form_for [:admin,@invoice] do |f| %>
                <div class="row">
                  <div class="col-md-2">
                    <!-- Master part -->
                      <div class="content">
                        <%= render 'form_master' ,f: f %>
                      </div>
                  </div>

                  <div class="col-md-10">
                    <!-- Details Header -->
                    <div class="row">
                      <div class="col-md-7">
                        <p>Name</p>
                      </div>
                      <div class="col-md-1">
                        <p>Width</p>
                      </div>
                      <div class="col-md-1">
                        <p>Length</p>
                      </div>
                      <div class="col-md-1">
                        <p>Quantity</p>
                      </div>
                      <div class="col-md-1">
                        <p>Price</p>
                      </div>
                    </div>
                    <!-- Detail Fields -->
                    <div class="invoices">
                      <%= f.simple_fields_for :productions do |production| %>
                        <%= render 'production_fields' , f: production %>
                      <% end %>
                      <div class="links">
                        <%= link_to_add_association "Add", f , :productions , class: 'btn btn-md btn-success' %>
                      </div>
                    </div>
                  </div>

                    <!-- Button Add Dynamic Productions -->
                    <div class="form-group" style="padding: 15px;">
                      <%= f.submit class: 'btn btn-lg btn-primary'%>
                    </div>
                    <% end %>
                </div>
            </div>
          </div><!-- row-->
        </div><!-- Box Body-->
      </div><!-- Warning-->
    </div><!-- Content-->
  </div>
</div>

app/views/admin/invoices/_form_master.html.erb
<div class="form-group">
  <%= f.label 'អតិថិជន' %>
  <%= f.collection_select(:customer_id, Customer.all, :id, :name_with_contact, {:prompt => true} )  %>
</div>
<div class="form-group">
  <%= f.label :release_date%>
  <div class="input-group date">
    <div class="input-group-addon">
      <i class="fa fa-calendar"></i>
    </div>
    <%= f.text_field :release_date, data:{ provide:'datepicker'} , class: 'datepicker form-control'%>
  </div>
</div>
<!-- </div> -->
<div class="form-group">
  <%= f.label :deposit%>
  <div class="input-group">
    <span class="input-group-addon">$</span>
    <%= f.text_field :deposit , class: "form-control" %>
  </div>
</div>

app/views/admin/invoices/_production_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="form-group col-md-7">
      <%= f.text_area :name , class:"form-control" , placeholder: "Name"%>
    </div>
    <div class="form-group col-md-1">
      <%= f.text_field :width , class:"form-control" , placeholder: "Width"%>
    </div>
    <div class="form-group col-md-1">
      <%= f.text_field :length , class:"form-control" , placeholder: "Length"%>
    </div>
    <div class="form-group col-md-1">
      <%= f.text_field :quantity , class:"form-control" , placeholder: "Quntity"%>
    </div>
    <div class="form-group col-md-1">
      <%= f.text_field :price , class:"form-control" , placeholder: "Price"%>
    </div>
    <div class="form-group col-md-1">
      <%= link_to_remove_association(f) do %>
        <i class="btn btn-danger">Remove</i>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/invoices/_show_master.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Invoice</h3><hr>
    <div class="box-body no-padding no-border"></div>
    <div class="row">
      <div class="col-md-9">
        <p><b>Customer ID</b></p>
        <p><b>Customer Name</b></p>
        <p><b>Release Date</b></p>
        <p><b>Total</b></p>
        <p><b>Deposit</b></p>
      </div>
      <div class="col-md-3">
        <p><%= @invoice.customer.id %></p>
        <p><%= @invoice.customer.name %></p>
        <p><%= @invoice.release_date.to_formatted_s(:rfc822) %></p>
        <p><%= number_to_currency(@invoice.total) %></p>
        <p><%= number_to_currency(@invoice.deposit) %></p>
      </div>
    </div>
  </div>
</div>

app/views/admin/invoices/_show_payment.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Payments Histroy</h3><br><br>
    <div class="box-body no-padding">
      <table class="table table-hover table-responsive">
        <tbody>
          <tr>
            <th>No</th>
            <th>Invoice Number</th>
            <th>Paid Date</th>
            <th>Amount</th>
            <th>Action</th>
          </tr>
          <% @payments.each_with_index do |payment,index| %>
          <tr>
            <td><%= index +1%></td>
            <td><%= payment.invoice_id %></td>
            <td><%= payment.paid_date.to_formatted_s(:rfc822) %></td>
            <td><%= payment.amount %></td>
            <td>
              <%= link_to "Edit", edit_admin_payment_path(payment), class: "btn btn-sm btn-warning " %>
              <%= link_to "Delete", admin_payment_path(payment), class: "btn btn-sm btn-danger " , method: :delete, data: {confirm: "Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <hr>
    <div class="pull-right" style="margin-right: 50px;">
      <h6><b>Total: <%= number_to_currency(@invoice.total) %></b></h6>
      <h6><b>Deposit: <%= number_to_currency(@invoice.deposit) %></b></h6>
      <% if @balance == "PAID" %>
        <h6><b>Balance: <%= @balance %></b></h6>
      <%else %>
        <h6><b>Balance: <%= number_to_currency(@balance) %></b></h6>
      <% end %>
    </div>
      <%= link_to "បង់ប្រាក់" , new_admin_payment_path(id: @invoice.id) , class: "btn btn-lg btn-primary"%>
  </div>
</div>

app/views/admin/invoices/_show_productions.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Productions</h3><br><br>
    <div class="box-body no-padding no-border">
      <table class="table table-hover table-responsive">
        <tbody>
          <tr>
            <th>No</th>
            <th>Invoice Number</th>
            <th>Production Name</th>
            <th>Width</th>
            <th>Length</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
            <th>Action</th>
          </tr>
          <% @invoice.productions.each_with_index do |production,index| %>
          <tr>
            <td><%= index +1%></td>
            <td><%= production.invoice_id %></td>
            <td><%= production.name %></td>
            <td><%= production.width %>m</td>
            <td><%= production.length %>m</td>
            <td><%= production.quantity %></td>
            <td><%= number_to_currency(production.price) %></td>
            <td><%= number_to_currency(@total_price) %></td>
            <td>
              <%= link_to "Edit", edit_admin_production_path(production), class: "btn btn-sm btn-warning " %>
              <%= link_to "Delete", admin_production_path(production), class: "btn btn-sm btn-danger " , method: :delete, data: {confirm: "Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/admin/invoices/index.html.erb
<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Invoice
      </h1>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">
            <i class="fa fa-dashboard"></i>
            Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#">Forms</a>
        </li>
        <li class="breadcrumb-item active">General Elements</li>
      </ol>
    </section>

    <div class="content">
      <div class="col-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Invoices</h3><br><br>
            <%= link_to "New Invoice" , new_admin_invoice_path , class: "btn btn-primary"%><br>
            <div class="box-tools">
              <div class="input-group input-group-sm" style="width: 150px;">
                <input name="table_search" class="form-control pull-right" placeholder="Search" type="text">
                <div class="input-group-btn">
                  <button type="submit" class="btn btn-default">
                    <i class="fa fa-search"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
          <!-- /.box-header -->
          <div class="box-body no-padding">
            <table class="table table-hover table-responsive">
              <tbody>
                <tr>
                  <th>Invoice NO</th>
                  <th>Customer Name</th>
                  <th>Release Date</th>
                  <th>Deposit</th>
                  <th>Total</th>
                  <th>Action</th>
                </tr>
                <% @invoices.each do |invoice| %>
                <tr>
                  <td>
                    <a href="javascript:void(0)"><%= invoice.id %></a>
                  </td>
                  <td><%= invoice.customer.name %></td>
                  <td>
                    <%= invoice.release_date.to_formatted_s(:rfc822)  %>
                  </td>
                  <td><%= invoice.deposit %></td>
                  <td>
                    <span><%= invoice.total %></span>
                  </td>
                  <td>
                    <%= link_to "View", admin_invoice_path(invoice) , class: "btn btn-sm btn-primary "%>
                    <%= link_to "Edit", edit_admin_invoice_path(invoice), class: "btn btn-sm btn-warning " %>
                    <%= link_to "Delete", admin_invoice_path(invoice), class: "btn btn-sm btn-danger " , method: :delete, data: {confirm: "Are you sure?"} %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
    </div>

  </div>
</div>

app/views/admin/invoices/new.html.erb
<%= render 'form' %>

app/views/admin/invoices/show.html.erb
<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <h1>Invoice Details </h1>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">
            <i class="fa fa-dashboard"></i>
            Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#">Forms</a>
        </li>
        <li class="breadcrumb-item active">General Elements</li>
      </ol>
    </section>

    <div class="content">
      <div class="row">
        <div class="col-md-5">
          <%= render 'show_master' %>
        </div>
        <div class="col-md-7">
          <%= render 'show_productions' %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= render 'show_payment' %>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/admin/invoices/test.html.erb
<div class="wrapper">
  <div class="content-wrapper">
    <h1>Test</h1>
    <%= simple_form_for [:admin,@invoice] do |f| %>
      <%= f.text_field :deposit %>
      <div class="invoices">
        <%= f.simple_fields_for :productions do |production| %>
          <%= render 'production_fields' , f: production %>
        <% end %>
        <div class="links">
          <%= link_to_add_association "Add", f , :productions  %>
        </div>
      </div>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/admin/payments/_form.html.erb
<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        New Customer Form
      </h1>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">
            <i class="fa fa-dashboard"></i>
            Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#">Forms</a>
        </li>
        <li class="breadcrumb-item active">General Elements</li>
      </ol>
    </section>
    <div class="content">
      <div class="box box-warning">
        <div class="box-header with-border">
          <h3 class="box-title">Add New Customer</h3>
        </div>
        <!-- /.box-header -->

        <div class="box-body">
          <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
              <%= form_for ([:admin,@payment]) do |f| %>
                <div class="form-group">
                  <%= f.label "លេខវិក័យប័ត្រ" %>
                  <%= f.label "#{@invoice.id}"%>
                </div>
                <div class="form-group">
                  <%= f.label "ថ្ងៃបង់ប្រាក់"%>
                  <div class="input-group date">
                    <div class="input-group-addon">
                      <i class="fa fa-calendar"></i>
                    </div>
                    <%= f.text_field :paid_date, data:{ provide:'datepicker'} , class: 'datepicker form-control'%>
                  </div>
                </div>
                <div class="form-group">
                  <%= f.label "ចំនួនទឹកប្រាក់"%>
                  <%= f.text_field :amount , class:"form-control" , placeholder: "ចំនួនទឹកប្រាក់"%>
                </div>
                <div class="form-group">
                  <%= f.submit  class: "btn btn-lg btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>

        </div>
        <!-- Box Body-->

      </div>
    </div>
  </div>
</div>

app/views/admin/payments/new.html.erb
<%= render 'form' %>