config/routes.rb
Rails.application.routes.draw do
  root 'admin/homes#index'
  namespace :admin do
    resources :dashboard
    resources :productions
    resources :payments
    resources :posts
    resources :homes
    resources :suppliers
    resources :customers
    resources :invoices

    devise_for :users, controllers: {
      sessions: 'admin/users/sessions' ,
      registrations: 'admin/users/registrations',
    }
  end

  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :invoices

  def name_with_contact
    "#{name}" " , #{contact}"
  end
end

app/models/import.rb
class Import < ApplicationRecord
  belongs_to :supplier
  has_many :import_details
  has_many :products , through: import_details
end

app/models/import_detail.rb
class ImportDetail < ApplicationRecord
  belongs_to :product
  belongs_to :import
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :payments
  accepts_nested_attributes_for :payments, :allow_destroy => true, :reject_if => :all_blank
  has_many :productions, inverse_of: :invoice
  accepts_nested_attributes_for :productions, :allow_destroy => true, :reject_if => :all_blank

  def self.total_price_in_invoice(invoice)
    total = 0
      invoice.productions.each do |productions|
      total = productions.width * productions.length * productions.price
    end
    return total
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :invoice
  def self.total_price_in_payment(invoice)
    payments = where(invoice: invoice)
    total =0;
    payments.each do |payment|
      total = total + payment.amount
    end
    return total
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :import_details
  has_many :imports , through: :import_details
end

app/models/production.rb
class Production < ApplicationRecord
  belongs_to :invoice ,optional: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :imports
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::ApplicationController
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/invoices_helper.rb
module Admin::InvoicesHelper



end

app/helpers/admin/payments_helper.rb
module Admin::PaymentsHelper
end

app/helpers/admin/productions_helper.rb
module Admin::ProductionsHelper
end

app/helpers/admin/suppliers_helper.rb
module Admin::SuppliersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def self.check_balance(total,deposit)
    if total < deposit && total < deposit - 5
      return "PAID"
    else
      return total -  deposit
    end

  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/shared/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right d-none d-sm-inline-block">
    <b>Version</b> 1.2.1
  </div>Copyright &copy; 2017 <a href="#">Gino Emotional</a>. All Rights Reserved.
</footer>

app/views/admin/shared/_leftsidebar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="image">
        <%= image_tag("/images/user2-160x160.jpg" ,class: "rounded-circle") %>
      </div>
      <div class="info">
        <p>Gino Emotion</p>
        <a href="#">
          <i class="fa fa-circle text-success"></i>
          Online</a>
      </div>
    </div>
    <!-- search form -->
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat">
            <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    </form>
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li>
        <a href="dashboard">
          <i class="fa fa-dashboard"></i>
          <span>Dashboard</span>
        </a>
      </li>

      <!-- Customers -->
      <li>
        <%= link_to admin_customers_path do %>
        <i class="fa fa-envelope"></i>
        <span>Customer</span>
        <span class="pull-right-container">
          <small class="label pull-right bg-yellow">12</small>
          <small class="label pull-right bg-green">16</small>
          <small class="label pull-right bg-red">5</small>
        </span>
        <% end %>
      </li>

      <!-- Supplier -->
      <li>
        <%= link_to admin_suppliers_path do %>
        <i class="fa fa-envelope"></i>
        <span>Suppliers</span>
        <span class="pull-right-container">
          <small class="label pull-right bg-yellow">12</small>
          <small class="label pull-right bg-green">16</small>
          <small class="label pull-right bg-red">5</small>
        </span>
        <% end %>
      </li>

      <!-- Invoices -->
      <li>
        <%= link_to admin_invoices_path do %>
        <i class="fa fa-envelope"></i>
        <span>Invoices</span>
        <span class="pull-right-container">
          <small class="label pull-right bg-yellow">12</small>
          <small class="label pull-right bg-green">16</small>
          <small class="label pull-right bg-red">5</small>
        </span>
        <% end %>
      </li>

    </ul>
  </section>
  <!-- /.sidebar -->
  <div class="sidebar-footer">
    <!-- item-->
    <a href="#" class="link" data-toggle="tooltip" title="" data-original-title="Settings">
      <i class="fa fa-cog fa-spin"></i>
    </a>
    <!-- item-->
    <a href="#" class="link" data-toggle="tooltip" title="" data-original-title="Email">
      <i class="fa fa-envelope"></i>
    </a>
    <!-- item-->
    <a href="#" class="link" data-toggle="tooltip" title="" data-original-title="Logout">
      <i class="fa fa-power-off"></i>
    </a>
  </div>
</aside>

app/views/admin/shared/_navigation.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">MAX</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Admin </b>Dashboard</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="../images/user2-160x160.jpg" class="user-image rounded-circle" alt="User Image">
            <span class="d-none d-sm-inline-block">Gino Emtion</span>
          </a>
          <ul class="dropdown-menu scale-up">
            <!-- User image -->
            <li class="user-header">
              <img src="../images/user2-280x90.jpg" class="img-fluid" alt="User Image">

              <p>
                MultiPurpose Themes
                <small>Member since April . 2016</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="row">
                <div class="col text-center">
                  <a href="#">Followers</a>
                </div>
                <div class="col text-center">
                  <a href="#">Friends</a>
                </div>
                <div class="col text-center">
                  <a href="#">Sales</a>
                </div>
              </div>
              <!-- /.row -->
            </li>
            <!-- Menu Footer-->
            <div class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="#" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </div>
          </ul>
        </li>
        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope"></i>
            <span class="label label-success">5</span>
          </a>
          <ul class="dropdown-menu scale-up">
            <li class="header">You have 5 messages</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu inner-content-div">
                <li><!-- start message -->
                  <a href="#">
                    <div class="pull-left">
                      <img src="images/user2-160x160.jpg" class="rounded-circle" alt="User Image">
                    </div>
                    <div class="mail-contnet">
                       <h4>
                        Lorem Ipsum
                        <small><i class="fa fa-clock-o"></i> 15 mins</small>
                       </h4>
                       <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>
                    </div>
                  </a>
                </li>
                <!-- end message -->
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="images/user3-128x128.jpg" class="rounded-circle" alt="User Image">
                    </div>
                    <div class="mail-contnet">
                       <h4>
                        Nullam tempor
                        <small><i class="fa fa-clock-o"></i> 4 hours</small>
                       </h4>
                       <span>Curabitur facilisis erat quis metus congue viverra.</span>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="images/user4-128x128.jpg" class="rounded-circle" alt="User Image">
                    </div>
                    <div class="mail-contnet">
                       <h4>
                        Proin venenatis
                        <small><i class="fa fa-clock-o"></i> Today</small>
                       </h4>
                       <span>Vestibulum nec ligula nec quam sodales rutrum sed luctus.</span>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="images/user3-128x128.jpg" class="rounded-circle" alt="User Image">
                    </div>
                    <div class="mail-contnet">
                       <h4>
                        Praesent suscipit
                      <small><i class="fa fa-clock-o"></i> Yesterday</small>
                       </h4>
                       <span>Curabitur quis risus aliquet, luctus arcu nec, venenatis neque.</span>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="images/user4-128x128.jpg" class="rounded-circle" alt="User Image">
                    </div>
                    <div class="mail-contnet">
                       <h4>
                        Donec tempor
                        <small><i class="fa fa-clock-o"></i> 2 days</small>
                       </h4>
                       <span>Praesent vitae tellus eget nibh lacinia pretium.</span>
                    </div>
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">See all e-Mails</a></li>
          </ul>
        </li>
        <!-- Notifications: style can be found in dropdown.less -->
        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell"></i>
            <span class="label label-warning">7</span>
          </a>
          <ul class="dropdown-menu scale-up">
            <li class="header">You have 7 notifications</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu inner-content-div">
                <li>
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> Curabitur id eros quis nunc suscipit blandit.
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-warning text-yellow"></i> Duis malesuada justo eu sapien elementum, in semper diam posuere.
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-users text-red"></i> Donec at nisi sit amet tortor commodo porttitor pretium a erat.
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-shopping-cart text-green"></i> In gravida mauris et nisi
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-user text-red"></i> Praesent eu lacus in libero dictum fermentum.
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-user text-red"></i> Nunc fringilla lorem
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-user text-red"></i> Nullam euismod dolor ut quam interdum, at scelerisque ipsum imperdiet.
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
          </ul>
        </li>
        <!-- Tasks: style can be found in dropdown.less -->
        <li class="dropdown tasks-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-flag"></i>
            <span class="label label-danger">6</span>
          </a>
          <ul class="dropdown-menu scale-up">
            <li class="header">You have 6 tasks</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu inner-content-div">
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Lorem ipsum dolor sit amet
                      <small class="pull-right">30%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-aqua" style="width: 30%;" role="progressbar"
                           aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">30% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Vestibulum nec ligula
                      <small class="pull-right">20%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-danger" style="width: 20%;" role="progressbar"
                           aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Donec id leo ut ipsum
                      <small class="pull-right">70%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-light-blue" style="width: 70%;" role="progressbar"
                           aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">70% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Praesent vitae tellus
                      <small class="pull-right">40%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-yellow" style="width: 40%;" role="progressbar"
                           aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">40% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Nam varius sapien
                      <small class="pull-right">80%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-red" style="width: 80%;" role="progressbar"
                           aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">80% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Nunc fringilla
                      <small class="pull-right">90%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-primary" style="width: 90%;" role="progressbar"
                           aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">90% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
              </ul>
            </li>
            <li class="footer">
              <a href="#">View all tasks</a>
            </li>
          </ul>
        </li>
        <!-- Control Sidebar Toggle Button -->
        <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-cog fa-spin"></i></a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="hold-transition skin-blue sidebar-mini">
    <%= render "admin/shared/navigation" %>

    <!-- Left side column. contains the logo and sidebar -->
    <%= render "admin/shared/leftsidebar" %>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="hold-transition skin-blue sidebar-mini">
    <%= yield %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>